const questionsTest = [
  {
    id: 1,
    img: 'https://i.imgur.com/70wRydJ.jpg',
    text: 'В каком году прошел первый розыгрыш OLIMPBET Суперкубка России?',
    correct: '2003',
    variant1: '1996',
    variant2: '1999',
    variant3: '2003',
    variant4: '2006',
    date: '1655018831',
    // date: '1656745200',
  },
  {
    id: 2,
    img: 'https://i.imgur.com/JDdsVLp.jpg',
    text: 'Кто выиграл в первом розыгрыше OLIMPBET Суперкубка России?',
    correct: 'Локомотив',
    variant1: 'Локомотив',
    variant2: 'ЦСКА',
    variant3: 'Терек',
    variant4: 'Динамо',
    date: '1655018831',
  },
  {
    id: 3,
    img: 'https://i.imgur.com/uTeobcB.jpg',
    text: 'Какой клуб больше всех брал OLIMPBET Суперкубок России?',
    correct: 'ЦСКА',
    variant1: 'Зенит',
    variant2: 'Спартак',
    variant3: 'Локомотив',
    variant4: 'ЦСКА',
    date: '1655018831',
  },
  {
    id: 4,
    img: 'https://i.imgur.com/cLMxIHN.jpg',
    text: 'Какой из этих клубов никогда не играл в OLIMPBET Суперкубке России?',
    correct: 'Динамо',
    variant1: 'Рубин',
    variant2: 'Терек',
    variant3: 'Динамо',
    variant4: 'Ростов',
    date: '1655018831',
  },
  {
    id: 5,
    img: 'https://i.imgur.com/7jQtkk9.jpg',
    text: 'Кто является лучшим бомбардиром в истории OLIMPBET Суперкубке России? (2 игрока)',
    correct: 'Жо + Сердар Азмун',
    variant1: 'Жо + Сердар Азмун',
    variant2: 'Артем Дзюба + Федор Смолов',
    variant3: 'Алексей Миранчук + Хонда',
    variant4: 'Вагнер Лав — Алан Дзагоев',
    date: '1655018831',
  },
  {
    id: 6,
    img: 'https://i.imgur.com/LCJNtzc.jpg',
    text: 'С каким счетом закончился прошлогодний розыгрыш OLIMPBET Суперкубка России?',
    correct: 'Зенит 3-0 Локомотив',
    variant1: 'Зенит 1-1 Локомотив',
    variant2: 'Зенит 2-0 Локомотив',
    variant3: 'Зенит 0-1 Локомотив',
    variant4: 'Зенит 3-0 Локомотив',
    date: '1655018831',
  },
  {
    id: 7,
    img: 'https://i.imgur.com/iNhrmJh.jpg',
    text: 'Кто из тренеров больше всех брал трофей OLIMPBET Суперкубок России?',
    correct: 'Юрий Семин',
    variant1: 'Юрий Семин',
    variant2: 'Леонид Слуцкий',
    variant3: 'Валерий Газаев',
    variant4: 'Зенит 3-0 Локомотив',
    date: '1655018831',
  },
  {
    id: 8,
    img: 'https://i.imgur.com/AwaV3Hf.jpg',
    text: 'В каком из этих городов раннее не проводился OLIMPBET Суперкубок России?',
    correct: 'Казань',
    variant1: 'Калининград',
    variant2: 'Самара',
    variant3: 'Ростов',
    variant4: 'Казань',
    date: '1655018831',
  },
  {
    id: 9,
    img: 'https://i.imgur.com/tpD2AFL.jpg',
    text: 'Какой клуб не смог принять участие в OLIMPBET Суперкубке России из-за финансовых проблем?',
    correct: 'Тосно',
    variant1: 'Тосно',
    variant2: 'Москва',
    variant3: 'Амкар',
    variant4: 'Кубань',
    date: '1655018831',
  },
  {
    id: 10,
    img: 'https://i.imgur.com/lEo4mbZ.jpg',
    text: 'В каком году OLIMPBET Суперкубок России собрал больше всего зрителей на стадионе?',
    correct: '2008',
    variant1: '2021',
    variant2: '2011',
    variant3: '2018',
    variant4: '2008',
    date: '1655018831',
  },
  {
    id: 11,
    img: 'https://i.imgur.com/R7vYE51.jpg',
    text: 'Кто из данных игроков выиграл OLIMPBET Суперкубок России с тремя разными клубами?',
    correct: 'Сергей Семак',
    variant1: 'Денис Глушаков',
    variant2: 'Сергей Семак',
    variant3: 'Роман Широков',
    variant4: 'Юрий Жирков',
    date: '1655018831',
  },
  {
    id: 12,
    img: 'https://i.imgur.com/fagiNIg.jpg',
    text: 'Кто автор самого быстрого гола в истории OLIMPBET Суперкубок России?',
    correct: 'Вагнер Лав',
    variant1: 'Вагнер Лав',
    variant2: 'Егор Титов',
    variant3: 'Дмитрий Лоськов',
    variant4: 'Андрей Аршавин',
    date: '1655018831',
  },
  {
    id: 13,
    img: 'https://i.imgur.com/r2NgXBQ.jpg',
    text: 'Кто автор самого позднего гола в истории OLIMPBET Суперкубок России? ',
    correct: 'Марио Фернандеш',
    variant1: 'Марио Фернандеш',
    variant2: 'Квинси Промес',
    variant3: 'Сальваторе Боккетти',
    variant4: 'Ведран Чорлука',
    date: '1655018831',
  },
  {
    id: 14,
    img: 'https://i.imgur.com/dsoX37y.jpg',
    text: 'Кто забил единственный гол в розыгрыше OLIMPBET Суперкубка России 2005 года?',
    correct: 'Дмитрий Лоськов',
    variant1: 'Марат Измайлов',
    variant2: 'Дмитрий Сычев',
    variant3: 'Дмитрий Лоськов',
    variant4: 'Динияр Билялетдинов',
    date: '1655018831',
  },
  {
    id: 15,
    img: 'https://i.imgur.com/PiLbmBv.jpg',
    text: 'В каком году был самый результативный розыгрыш OLIMPBET Суперкубка России?',
    correct: '2007',
    variant1: '2017',
    variant2: '2008',
    variant3: '2007',
    variant4: '2009',
    date: '1655018831',
  },
];

module.exports = questionsTest;
